const dummy={ 
    expense: [
          {
            id:15,
            amount: 200.0,
            category: "Rent",
            date: "01/04/2024",
            description: "Monthly rent payment",
            color: "rgb(255, 0, 0)",
          },
          {
            id:14,
            amount: 50.0,
            category: "Utilities",
            date: "10/05/2024",
            description: "Utility bills",
            color: "rgb(0, 0, 255)",
          },
          {
            id:13,
            amount: 300.0,
            category: "Groceries",
            date: "15/06/2024",
            description: "Monthly grocery shopping",
            color: "rgb(0, 128, 0)",
          },
          {
            id:12,
            amount: 150.0,
            category: "Dining",
            date: "05/08/2024",
            description: "Dinner at a restaurant",
            color: "rgb(255, 255, 0)",
          },
          {
            id:11,
            amount: 50.0,
            category: "Healthcare",
            date: "10/09/2024",
            description: "Medical check-up",
            color: "rgb(128, 0, 128)",
          },
          {
            id:10,
            amount: 800.0,
            category: "Travel",
            date: "15/10/2024",
            description: "Weekend getaway",
            color: "rgb(0, 0, 128)",
          },
          {
            id:9,
            amount: 200.0,
            category: "Insurance",
            date: "01/11/2024",
            description: "Insurance premium",
            color: "rgb(0, 128, 128)",
          },
          {
            id:8,
            amount: 600.0,
            category: "Clothing",
            date: "15/12/2024",
            description: "Clothing shopping",
            color: "rgb(128, 128, 0)",
          },
          {
            id:7,
            amount: 75.0,
            category: "Education",
            date: "05/01/2025",
            description: "Online course",
            color: "rgb(0, 128, 0)",
          },
          {
            id:6,
            amount: 120.0,
            category: "Fitness",
            date: "10/02/2025",
            description: "Gym membership",
            color: "rgb(0, 0, 255)",
          },
          {
            id:5,
            amount: 250.0,
            category: "Electronics",
            date: "15/03/2025",
            description: "New smartphone",
            color: "rgb(255, 0, 0)",
          },
          {
            id:4,
            amount: 80.0,
            category: "Hobbies",
            date: "20/04/2025",
            description: "Art supplies",
            color: "rgb(128, 0, 128)",
          },
          {
            id:3,
            amount: 150.0,
            category: "Gift",
            date: "01/05/2025",
            description: "Friend's birthday gift",
            color: "rgb(255, 255, 0)",
          },
          {
            id:2,
            amount: 300.0,
            category: "Home",
            date: "10/06/2025",
            description: "Furniture purchase",
            color: "rgb(128, 128, 0)",
          },
               {
            id:1,
            amount: 100.0,
            category: "Entertainment",
            date: "20/07/2024",
            description: "Concert tickets",
            color: "rgb(128, 0, 0)",
          },
        ],
    income: [
      {
        id:15,
        amount: 1500.0,
        category: "Salary",
        date: "15/01/2023",
        description: "Monthly salary deposit",
        color: "rgb(255, 0, 0)",
      },
      {
        id:14,
        amount: 500.0,
        category: "Bonus",
        date: "05/02/2023",
        description: "Year-end bonus",
        color: "rgb(0, 255, 0)",
      },
      {
        id:13,
        amount: 800.0,
        category: "Freelance",
        date: "10/03/2023",
        description: "Web development project",
        color: "rgb(0, 0, 255)",
      },
      {
        id:12,
        amount: 1200.0,
        category: "Investment",
        date: "20/04/2023",
        description: "Dividend payout",
        color: "rgb(255, 255, 0)",
      },
      {
        id:11,
        amount: 600.0,
        category: "Salary",
        date: "15/05/2023",
        description: "Monthly salary deposit",
        color: "rgb(255, 0, 255)",
      },
      {
        id:10,
        amount: 300.0,
        category: "Gift",
        date: "01/06/2023",
        description: "Birthday gift",
        color: "rgb(0, 255, 255)",
      },
      {
        id:9,
        amount: 1000.0,
        category: "Freelance",
        date: "08/07/2023",
        description: "Graphic design project",
        color: "rgb(128, 0, 128)",
      },
      {
        id:8,
        amount: 700.0,
        category: "Salary",
        date: "15/08/2023",
        description: "Monthly salary deposit",
        color: "rgb(128, 128, 0)",
      },
      {
        id:7,
        amount: 400.0,
        category: "Investment",
        date: "25/09/2023",
        description: "Stock dividends",
        color: "rgb(0, 128, 128)",
      },
      {
        id:6,
        amount: 900.0,
        category: "Bonus",
        date: "10/10/2023",
        description: "Quarterly performance bonus",
        color: "rgb(128, 0, 0)",
      },
      {
        id:5,
        amount: 1100.0,
        category: "Salary",
        date: "15/11/2023",
        description: "Monthly salary deposit",
        color: "rgb(0, 128, 0)",
      },
      {
        id:4,
        amount: 750.0,
        category: "Freelance",
        date: "05/12/2023",
        description: "Content writing project",
        color: "rgb(0, 0, 128)",
      },
      {
        id:3,
        amount: 950.0,
        category: "Gift",
        date: "01/01/2024",
        description: "New Year's gift",
        color: "rgb(192, 192, 192)",
      },
      {
        id:2,
        amount: 600.0,
        category: "Salary",
        date: "15/02/2024",
        description: "Monthly salary deposit",
        color: "rgb(128, 128, 128)",
      },
      {
        id:1,
        amount: 300.0,
        category: "Investment",
        date: "20/03/2024",
        description: "Mutual fund interest",
        color: "rgb(255, 165, 0)",
      },
    ]
}

export default dummy